### ISSUE TITLE
HTTP 1.1 multipart/form-data is not supported (chunks)

### ISSUE THREAD

**Issue by antonini** [yegor256/takes#372]
When I try to upload large files using a `multipart/form-data` form, server's throws an error saying that `there is no LF after CR in header, line #%d: \"%s\.` on class RqLive.

To reproduce this error, run netbout in debug and put a breakpoint on that line. Try to upload a file with more that 5 mb.

Browser will try to upload the file in chunks, but takes does not support that.

**Comment by yegor256** [comment]
@antonini can you please suggest a test, which will reproduce this problem?

**Comment by antonini** [comment]
@yegor256 Need to be a unit test? Or some steps to reproduce inside a real project, such as Netbout?

**Comment by yegor256** [comment]
@antonini just a unit test

**Comment by antonini** [comment]
@yegor256 I couldn't create a unit test that simulate that action, but what I saw is that we don't support chunked-body upload.

I was reading (RFC7230)[https://tools.ietf.org/html/rfc7230] the (Chunked Transfer Coding Section)[https://tools.ietf.org/html/rfc7230#page-36] and I didn't found that implemented on takes.

Netbout use takes, and I was able to receive an error when I tried to upload files larger then 5mb. Google Chrome split the file in chunks (trailers) and netbout return an error.

**Comment by yegor256** [comment]
@antonini now it's clear, thanks!

**Comment by davvd** [comment]
@antonini I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@antonini since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@antonini thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-82A07418AK0281203`

**Comment by davvd** [comment]
@mstzn36 this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by mstzn36** [comment]
@antonini I couldn't reproduce this bug in my local.I tried to run netbout in debug then upload 6mb file but server didn't throw any error. Can you help  please ?

**Comment by antonini** [comment]
@mstzn36 Server doesn't throw errors. To get that error I had to debug it. Have you tried to download the file after uploading it?

**Comment by mstzn36** [comment]
@antonini Yes I did. But size of the downloaded file was 0 bytes. Also i put a breakpoint on RqLive class,it didn't stop :( What is type of file which you try to upload ?

**Comment by antonini** [comment]
@mstzn36 So, you got the point. The downloaded file is "0" because you didn't uploaded it. Netbout hide exception that I said on issue description. What I suggested is to debug the upload process. I don't remember right now the class that throws it. What I saw is that because you are trying to upload a large file, the browser opens a lot of connections pushing small chunks. When I debugged HTTP that was been sent to server I saw that the last line of the first connection refers to "trailer".
What I suggest is to search on the source code the error that I describe on the issue description an put a breakpoint over there. You'll see that.

**Comment by mstzn36** [comment]
@antonini  But the result didn't change with the smaller file(151 kb).The downloaded file was still 0. I tried to debug on take and netbout but didn't see any error :( And the local server handled the uploaded file successfully (I checked size of the uploaded file.) I can't reproduce this bug on my local machine :(

Also when I tried to upload 6 MB file on my netbout account, it gave me below error.

<code>java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:387)
	at org.takes.rq.RqMultipart$Base.copy(RqMultipart.java:277)
	at org.takes.rq.RqMultipart$Base.make(RqMultipart.java:248)
	at org.takes.rq.RqMultipart$Base.buildRequests(RqMultipart.java:222)
	at org.takes.rq.RqMultipart$Base.(RqMultipart.java:140)
	at com.netbout.rest.bout.TkAttach.act(TkAttach.java:94)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:</code>

**Comment by antonini** [comment]
@mstzn36 I think that the problem was solved on PR #328.
I just uploaded and downloaded a zip and a pdf file of 9mb to netbout.

@yegor256 Can you confirm that?

**Comment by mstzn36** [comment]
@antonini try to upload a txt file which is larger than 5 mb to netbout and you will get that error. It seems there is a problem with txt file.

**Comment by antonini** [comment]
@mstzn36 I just uploaded an txt with 1kb and another with 9mb. And everything worked fine.

**Comment by mstzn36** [comment]
@antonini I created a new bout and uploaded file.It didn't throw any error. I guess the problem was with my bout which was created by https://github.com/yegor256/netbout/issues/758.
Anyway we can upload and download large files. I can't still reproduce this bug :(

**Comment by antonini** [comment]
@mstzn36 Have you tried with a bout created from web page?

**Comment by mstzn36** [comment]
@antonini yes of course.It did not give any error.

**Comment by antonini** [comment]
@mstzn36 So I think you don't need to change anything.

@yegor256 or @davvd Can you confirm it?

**Comment by yegor256** [comment]
@antonini it's your ticket, you're free to close it any moment

**Comment by antonini** [comment]
@yegor256 Ok.

**Comment by antonini** [comment]
@davvd I just checked and is working fine right now. I think PR #328 fixed that problem too.

**Comment by davvd** [comment]
> @davvd I just checked and is working fine right now. I think PR #328 fixed that problem too.

@antonini just close the ticket?

**Comment by antonini** [comment]
@davvd Sorry, didn't understood what you me with your question.

**Comment by davvd** [comment]
> @davvd Sorry, didn't understood what you me with your question.

@antonini the ticket is closed, we're good here

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd There was no solution provided in this ticket. So the quality is bad here.

**Comment by davvd** [comment]
> @davvd There was no solution provided in this ticket. So the quality is bad here.

@elenavolokhova thank you for paying attention

**Comment by davvd** [comment]
@mstzn36 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 64381283

**Comment by mstzn36** [comment]
@davvd will I get 30 points ?

**Comment by davvd** [comment]
> @davvd will I get 30 points ? 

@mstzn36 of course, in a few hours
