### ISSUE TITLE
AbstractHmBody.java:60-63: Right now the describeTo...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#795]
The puzzle `485-6f864529` from #485 has to be resolved:

https://github.com/yegor256/takes/blob/a98eb9681cd67703409dc0637dba93766676941a/src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java#L60-L63

The puzzle was created by rultor on 09-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#795](https://github.com/yegor256/takes/issues/795) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#795](https://github.com/yegor256/takes/issues/795) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/650752656). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
Fixed in #830

**Comment by t-izbassar** [comment]
@0crat waiting for #830 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #830 to be merged ([here](https://github.com/yegor256/takes/issues/795#issuecomment-372608718))

@t-izbassar The impediment for [#795](https://github.com/yegor256/takes/issues/795) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0pdd** [comment]
The puzzle `485-6f864529` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#832](https://github.com/yegor256/takes/issues/832) is still not solved.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#795](https://github.com/yegor256/takes/issues/795) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#832](https://github.com/yegor256/takes/issues/832) is solved here.
